language: go
go: 1.6.3

script:
  - if [ "${TRAVIS_TAG}" == "" ];
    then export VERSION=`git rev-parse --abbrev-ref HEAD`;
    else export VERSION=${TRAVIS_TAG:1};
    fi;
    if [ "${VERSION}" == "HEAD" ];
    then export VERSION=master;
    fi;
    export BUILD=`git rev-parse HEAD`;
    echo ${VERSION} ${BUILD}
  - make build
  - make test
  - make dist 
deploy:
  provider: releases
  api_key:
    secure: t+gv2I3ilkvP9O3EWjPiu/nSKzgUf1+lIpw5+CeG4yfqEY8LgfAYFELCqfBEygvNOq08whpMxh93xAS7eHhae+af4+SYIJ924th64XjlROrTMDy1n77kT2WKv61syNvy/+zpZBY+OS5f435MNhzln1C1sM74JVarACrAK4/swHXN9xHtUNggZosW4BA/cY0Gr7tZnWTf2A0qiqN2eUz8tSqdHrQ98dmBsRYNkKMIARUiyHGtCHZ7Ysz/5JQbLRbTgs/y4s7q5vwvEKSwvZapgMbzyOJhi85Hr1pAeYpEN3Ax8iw6Un8zyA+dzSmA3RZpkOuFQxSJaGHUj16mP5qvqgnCJsj8Oeg5wpzhFG2inAOxWc7+N+HTmxAIZWDF+isNuUfArjaYoQscqci/Kc1IPrPDj+JhAHfM3Y0yYhJYn7Dz9BpVn1GtblrlK2u43fjHFo4BiW/Zr4WW6kxP42A+9nYKkl8iHPxMjoBBhbA7bncitFCeVY9qIxAhaCPslHcKWPftvbMnSvGzQQd1GSE9BJlr/yiFvsdz+QxTDK090OLvH8LNhz+xpvrSmwz2NCkb/Wjll3wzsHb1eNL0vSB2XoHeTVIBfENhyDSDHlBJXkUinte6j12N/YcvYyS3oX+6XXU/9kTX/m5b38NwswFqzSkiFED8rzAD0j16q96ZhqE=
  file:
    - dist/docker-volume-glusterfs-${VERSION}-linux_amd64.zip
    - dist/docker-volume-glusterfs-${VERSION}-linux_amd64.tar.gz
    - dist/docker-volume-glusterfs-${VERSION}-linux_386.zip
    - dist/docker-volume-glusterfs-${VERSION}-linux_386.tar.gz
    - dist/docker-volume-glusterfs-${VERSION}-linux_arm.zip
    - dist/docker-volume-glusterfs-${VERSION}-linux_arm.tar.gz
    - dist/docker-volume-glusterfs-${VERSION}-darwin_amd64.zip
    - dist/docker-volume-glusterfs-${VERSION}-darwin_amd64.tar.gz
    - dist/docker-volume-glusterfs-${VERSION}-darwin_386.zip
    - dist/docker-volume-glusterfs-${VERSION}-darwin_386.tar.gz
    - dist/docker-volume-glusterfs-${VERSION}-freebsd_amd64.zip
    - dist/docker-volume-glusterfs-${VERSION}-freebsd_amd64.tar.gz
    - dist/docker-volume-glusterfs-${VERSION}-freebsd_386.zip
    - dist/docker-volume-glusterfs-${VERSION}-freebsd_386.tar.gz
    - dist/docker-volume-glusterfs-${VERSION}-windows_386.zip
    - dist/docker-volume-glusterfs-${VERSION}-windows_386.tar.gz
    - dist/docker-volume-glusterfs-${VERSION}-windows_amd64.zip
    - dist/docker-volume-glusterfs-${VERSION}-windows_amd64.tar.gz
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: watson81/docker-volume-glusterfs
